config/routes.rb
Pholder::Application.routes.draw do
  

  resources :users do
    resources :friends
    resources :albums do
      resources :photos
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :destroy, :update]

  resources :friendships, only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  resources :home, only: [:create]

  match '/contact',   to: 'home#contact'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete

  root :to => "home#index"

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
# before_filter :signed_i, :except => [:index, :show]

  def index
  	@user = User.find(params[:user_id])
  end

  def show
  	redirect_to user_path(params[:id])
  end

  def new
  	@friendship1 = Friendship.new
  	@friendship2 = Friendship.new
  end

  def create
  	@user = User.find(current_user)
  	@friend = User.find(params[:friend_id])
  	params[:friendship1] = { :user_id => @user.id, :friend_id => @friend.id, :status => 'requested' }
  	params[:friendship2] = { :user_id => @friend.id, :friend_id => @user.id, :status => 'pending'}
  	@friendship1 = Friendship.create(params[:friendship1])
  	@friendship2 = Friendship.create(params[:friendship2])
  	if @friendship1.save && @friendship2.save
  	  redirect_to user_friends_path(current_user)
  	else
  	  flash[:error] = "Unable to add friend."
  	  redirect_to user_path(current_user)
  	end
  end

  def update
  	@user = User.find(current_user)
  	@friend = User.find(params[:id])
  	params[:friendship1] = { :user_id => @user.id, :friend_id => @friend.id, :status => 'accepted' }
  	params[:friendship2] = { :user_id => @friend.id, :friend_id => @user.id, :status => 'accepted' }
  	@friendship1 = Friendship.find_by_user_id_and_friend_id(@user.id, @friend.id)
  	@friendship2 = Friendship.find_by_user_id_and_friend_id(@friend.id, @user.id)
  	if @friendship1.update_attributes(params[:friendship1]) && @friendship2.update_attributes(params[:friendship2])
  	  flash[:notice] = "Friend added."
  	  redirect_to user_friends_path(current_user)
  	else
  	  flash[:error] = "An error occured."
  	  redirect_to user_path(current_user)
  	end
  end

  def destroy
  	@user = User.find(params[:user_id])
  	@friend = User.find(params[:id])
  	@friendship1 = @user.friendships.find_by_friend_id(params[:id])
  	@friendship2 = @friend.friendships.find_by_friend_id(params[:user_id])
  	@friendship1.destroy
  	@friendship2.destroy
  	flash[:notice] = "Friend deleted." 
  	redirect_to user_friends_path(current_user)
  end

end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<% provide(:title, "Friends") %>

<div class="clearfix">

	<div class="editprofilelogo">
		<%= link_to (image_tag "formlogo.png", :width => "200"), user_path(current_user) %>
	</div>

	<h1 class="friends">My Friends</h1>

	<div class="friendsholder span12">
		<div class="pendingrequests span11">
			<h3 class="friends">Pending requests</h3>
			<% unless @user.pending_friends.empty? %>
				<% @user.pending_friends.each do |pending_friend| %>
				<div class="usersbox">
					<%= link_to pending_friend.name, user_path(pending_friend) %>

					<span class="floatright">
						<%= link_to "Accept", user_friend_path(:user_id => current_user.id, :id => pending_friend), :method => :put, :confirm => "Are you sure?" %>
						<%= link_to "Reject", user_friend_path(:user_id => current_user.id, :id => pending_friend), :method => :delete, :confirm => "Delete?" %>
					</span>
				</div>
				<% end %>
			<% else %>
				<div class="usersbox">
					You have no pending requests.
				</div>
			<% end %>
		</div>

		<div class="currentfriends span5">
			<h3 class="friends">Current Friends</h3>

			<% unless @user.friends.empty? %>
				<% @user.friends.each do |friend| %>
					<div class="usersbox">
						<%= link_to (image_tag friend.profilepic? ? friend.profilepic : "questionmark.png", :size => "50x50"), user_path(friend) %>
						<%= link_to friend.name, user_path(friend) %>
						<span class="floatright">
							<%= link_to "Remove", user_friend_path(:user_id => current_user.id, :id =>friend.id), :method => :delete, :confirm => "Delete friend?" %>
						</span>
					</div>
				<% end %>
			<% else %>
				<div class="usersbox">
					You currently have no friends. <%= link_to "Click here to find friends!", users_path %>
				</div>
			<% end %>
		</div>

		<div class="friendrequests span5 offset1">
			<h3 class="friends">Friend requests</h3>

			<% unless @user.requested_friends.empty? %>
				<% @user.requested_friends.each do |requested_friend| %>
					<div class="usersbox">
						<%= link_to (image_tag requested_friend.profilepic? ? requested_friend.profilepic : "questionmark.png", :size => "50x50"), user_path(requested_friend) %>
						<%= link_to requested_friend.name, user_path(requested_friend) %>
						<span class="floatright">
							<%= link_to "Cancel", user_friend_path(:user_id => current_user.id, :id => requested_friend), :method => :delete, :confirm => "Are you sure?" %>
						</span>
					</div>
				<% end %>
			<% else %>
				<div class="usersbox">
					You have no friend requests.
				</div>
			<% end %>

		</div>
	</div>
</div>