config/routes.rb
Pholder::Application.routes.draw do
  

  resources :users do
    resources :friends
    resources :albums do
      resources :photos
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :destroy, :update]

  resources :friendships, only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  resources :home, only: [:create]

  match '/contact',   to: 'home#contact'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete

  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password
  attr_accessible :email, :name, :password, :password_confirmation, :profilepic
  validates_presence_of :password, :on => :create

  validates_format_of :name, :with => /[A-Za-z]+/, :on => :create
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_uniqueness_of :email, :on => :create
  validates_length_of :password, :minimum => 5, :on => :create


  has_many :ownerships
  has_many :albums, :through => :ownerships 
  accepts_nested_attributes_for :albums

  has_many :friendships, :dependent => :destroy
  has_many :friends, :through => :friendships, :conditions => "status = 'accepted'"
  has_many :requested_friends, :through => :friendships, :source => :friend, :conditions => "status = 'requested'", :order => :created_at
  has_many :pending_friends, :through => :friendships, :source => :friend, :conditions => "status = 'pending'", :order => :created_at

  has_attached_file :profilepic,
            :storage => :s3,
            :s3_credentials => "#{Rails.root}/config/s3.yml",
            :path => "/:style/:id/:filename"

  before_save { |user| user.email = email.downcase }
  before_save { |user| if user.new_record? then create_remember_token end }

  def name_with_initial
    "#{name}"
  end

  def self.search(search)
    where('email LIKE ?', "%#{search}%")
  end

  def generate_token(column)
    self[column] = SecureRandom.urlsafe_base64
  end

  def send_password_reset
    generate_token(:password_reset_token)
    save!
    UserMailer.forgot_password(self).deliver
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	  if params[:search]
		@users = User.search(params[:search]).page(params[:page]).per_page(10)
	  else
	  	@users = User.order("email").page(params[:page]).per_page(10)
	  end
	end

	def new
	  @user = User.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @user }
      end
	end 

	def create
	  @user = User.new(params[:user])

	  respond_to do |format|
	  	if @user.save
	  	  UserMailer.registration_confirmation(@user).deliver
	  	  log_in(@user)
	  	  format.html { redirect_to @user, notice: "Welcome to Pholder, #{@user.name}!" }
	  	  format.json { render json: @user, status: :created, location: @user }
	  	else
	  	  format.html { render action: 'new' }
	  	  format.json { render json: @user.errors, status: :unprocessable_entity }
	  	end
      end
	end

	def show
	  @user = User.find(params[:id])
	  @albums = Album.all
	end

	def update
	  respond_to do |format|
	    if current_user.update_attributes(params[:user])
		  format.html { redirect_to current_user, notice: 'User successfully updated.'}
		  format.json { render json: current_user, status: :created, location: current_user }
		else
		  format.html { render action: 'edit' }
		  format.json { render json: current_user.errors, status: :unprocessable_entity }
		end
	  end
	end

	def edit
	  @user = User.find(params[:id])
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

<div class="formhold">
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div>
		<%= f.label :password_confirmation, "Confirm password" %>
		<%= f.password_field :password_confirmation %>
	</div>
	<div>
		<%= f.submit 'Submit', :class => 'submitbutton' %>
	</div>
</div>
<% end %>

app/views/users/_profilepic.html.erb
<%= link_to (image_tag user.profilepic? ? user.profilepic : "questionmark.png", :size => "50x50"), user_path(user) %>
<%= link_to user.name, user_path(user) %> <br>

app/views/users/edit.html.erb
<% provide(:title, 'Edit profile') %>


<div class="span12">
<div class="editprofilelogo">
	<%= link_to (image_tag "formlogo.png", :width => "200"), user_path(@user) %>
</div>

<%= form_for(@user) do |f| %>
<div>

	<div id="profpicbox" class="span4 offset1">
		<% if @user.profilepic? %>
		<%= image_tag @user.profilepic.url, :id => "userpic" %>
		<% end %>
	</div>
	
	<div class="editprofform span4">
		<div class="field">
			<%= f.label :profilepic, "Profile Picture" %>
			<%= f.file_field :profilepic %>
		</div>
		<div class="field">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :email %>
			<%= f.text_field :email %>
		</div>

		<div>
			<%= f.submit 'Submit', :class => 'submitbutton' %>
		</div>

		<%= link_to "Back", user_path(@user) %>
	</div>



	<% if @user.errors.any? %>
	<div id="error_exp">
		<h2><%= pluralize(@user.errors.count, "error") %> occurred.</h2>

		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	    </ul>
	</div>
	<% end %>
</div>

<% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>

<div class="clearfix">

	<div class="editprofilelogo">
		<%= link_to (image_tag "formlogo.png", :width => "200"), user_path(current_user) %>
	</div>

	<div class="span3">
		<%= form_tag users_path, :method => "get" do %>
			<%= label_tag(:search, "Search for user by email:") %>
			<%= text_field_tag :search, params[:search] %>
			<%= submit_tag "Search", :name => nil %>
		<% end %>

		<%= will_paginate @users %>
		<br>
	</div>

	<div class="allusers span8 offset1">

		<h1>All users</h1>

		<% @users.each do |user| %>
			<div class="usersbox">
				<%= link_to (image_tag user.profilepic? ? user.profilepic : "questionmark.png", :size => "50x50"), user_path(user) %>
				<%= link_to user.name, user_path(user) %> (<%= user.email %>)
				<% unless current_user.friends.include?(user) || current_user == user || current_user.requested_friends.include?(user) %>
					<span class="floatright"><%= link_to "Add friend", user_friends_path(:user_id => current_user.id, :friend_id => user.id), :method => :post %></span>
				<% end %>
				<% if current_user.friends.include?(user) %>
				<span class="floatright"><%= link_to "Remove friend", user_friends_path(:user_id => current_user.id, :friend_id => user.id), :method => :delete, :confirm => "Are you sure you want to remove #{user.name} from your friends?" %></span>
				<% end %>
			</div>
		<% end %>

	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>



<div class="span12 clearfix">
	<% if @user.errors.any? %>

		<% @user.errors.full_messages.each do |msg| %>
			<%= content_tag(:div, msg, class: "alert alert-error") %>
		<% end %>

	<% end %>
<div class="signupformholder span5 offset1">

	<h1>Sign Up</h1>

	<%= render 'form' %>

</div>

<div class="loginformholder span5">

	<h1>Already have an account?</h1>
	<%= render 'sessions/login' %>

</div>
</div>

app/views/users/show.html.erb
<% provide(:title, show_username) %>


<div class="container-fluid">
	<div class="row-fluid">


		<div class="span10 clearfix">

			<div class="numberofalbums">

				<% if current_user == @user %>
					<h1>You currently have <%= pluralize(@user.albums.count, "album") %></h1>
					<%= link_to "Create a new album!", new_user_album_path(@user) %>
				<% else %>
					<h1><%= @user.name %> currently has <%= pluralize(@user.albums.count, "album") %></h1>
				<% end %>

			</div>

			<div class="addtofriendsholder">
				<% if signed_in? %>
					<% unless @user == current_user || current_user.requested_friends.include?(@user) || current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
						<%= form_for(:friendship, :url => user_friends_path(:user_id => current_user.id, :friend_id => @user.id)) do |f| %>
						<%= f.submit "Add to my Friends" %>
						<% end %>
					<% end %>
				<% end %>


				<% if current_user == @user || @user.friends.include?(current_user) %>
					<% @user.albums.each do |album| %>
					<div class="albumthumb">
						<div class="albumpic">
							<%= link_to image_tag(!album.photos.empty? ? album.photos.first.avatar.url(:medium) : ("questionmark.png"), :size => "150x150"), user_album_path(@user, album) %>
						</div>
						<br>
						<%= album.name %>
					</div>
					<% end %>
				<% else %>
					<div>
						<h2>You are not friends with <%= @user.name %>.</h2>
					</div>
				<% end %>
			</div>

		</div>

				<div class="friendwrapper clearfix">
			<%= link_to (image_tag @user.profilepic? ? @user.profilepic : "questionmark.png", :size => "150x150", :class => "miniprofilepic"), (if current_user == @user then edit_user_path(@user) else user_path(@user) end) %> 

			<h4><%= user_name(@user) %> friends:</h4>
			<div class="textalignleft"> 
			<%= render :partial => 'profilepic', :collection => @user.friends, :as => :user %>
			</div>
		</div>

	</div>
</div>
			