config/routes.rb
Pholder::Application.routes.draw do
  

  resources :users do
    resources :friends
    resources :albums do
      resources :photos
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :destroy, :update]

  resources :friendships, only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  resources :home, only: [:create]

  match '/contact',   to: 'home#contact'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete

  root :to => "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :description, :user_ids, :status
  validates_presence_of :name

  has_many :ownerships
  has_many :users, :through => :ownerships
  has_many :photos

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

	def index
	  @user = User.find(params[:user_id])
	  @albums = @user.albums.all

	  respond_to do |format|
	  	format.html
	  	format.json { render json: @albums }
	  end
	end

	def show
	  @user = User.find(params[:user_id])
	  @album = @user.albums.find(params[:id])
	  @photos = @album.photos
	end

	def update
	  @user = User.find(params[:user_id])
	  @album = @user.albums.find(params[:id])
	  respond_to do |format|
		if @album.update_attributes(params[:album])
	      format.html { redirect_to user_album_path(@user, @album), notice: 'Album successfully updated' }
		else
		  format.html { render 'edit' }
		end
	  end
	end

	def edit
	  @user = User.find(params[:user_id])
	  @album = @user.albums.find(params[:id])
	end

	def create
	  @user = User.find(params[:user_id])
	  @album = @user.albums.build(params[:album])
	  if @user.save
		redirect_to user_album_path(@user, @album), notice: 'Album was successfully created.'
	  else
		render action: "new"
	  end
	end

	def new
	  @user = User.find(params[:user_id])
	  @album = Album.new
	end

	def destroy
	  @user = User.find(params[:user_id])
	  @album = @user.albums.find(params[:id])
	  @album.destroy
	  flash[:notice] = "Album successfully deleted."
	  redirect_to user_path(@user)
	end


end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for ([@user, @album]), :html => { :id => "uploadform" } do |f| %>
<div class="formholder">
	<%= f.label :name %>
	<%= f.text_field :name %>

	<br>
	<label>Hosts</label>

	<% if @user.friends.count != 0 %>
		<% @user.friends.each do |friend| %>
			<%= friend.name %>
			<%= check_box_tag 'album[user_ids][]', friend.id, @album.users.include?(friend) %>
		<% end %>
	<% else %>
		You currently have no friends. Find them <%= link_to "here", users_path %>.
	<% end %>

	<%= f.label :description %>
	<%= f.text_area :description, :rows => 10 %>

 	<br>

	<%=f.submit "Submit", :id => "newalbumbutton" %>
</div>
<% end %>


	

app/views/albums/_photodestroy.html.erb
<div class="picthumb" id="photo_<%= photo.id %>">
	<div class="albumpic">
		<%= link_to image_tag(photo.avatar.url ? photo.avatar.url(:small) : @album.name), root_url %>
		<br>
	</div>
	
	<%= link_to "Delete", user_album_photo_path(@user, @album, photo), :remote => true, method: :delete, :confirm => "Are you sure?", :class => "deletepiclink" %>
</div>

app/views/albums/edit.html.erb
<% provide(:title, "Edit album") %>


<div class="container-fluid">
	<div class="row-fluid">
		<div class="editalbumform span3">
			<%= render 'form' %>
		</div>

		<div class="clearfix">
			<div class="destroypicswrapper offset1 span8">
				<% if @album.photos.any? %>
					<%= render :partial => 'photodestroy', :collection => @album.photos, :as => :photo %>
				<% end %> 
			</div>
		</div>
	</div>
</div>

app/views/albums/new.html.erb
<% provide(:title, "Create a new album") %>

<div class="clearfix">
	<div class="span4 offset4">
		<h1>New Album</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/albums/show.html.erb
<% provide(:title, @album.name) %>


<div class="container-fluid">
	<div class="row-fluid">

		<div class="albumswrapper span10">
			<div class="numberofpictures">
				<h1><%= @album.name %></h1>
				<h3>This album currently has <%= pluralize(@album.photos.count, "photo") %></h3>

				<% if current_user.albums.include?(@album) %>
					<%= link_to "Upload new pics!", new_user_album_photo_path(@user, @album) %> |
					<%= link_to "Edit album", edit_user_album_path(@user, @album) %> |
					<%= link_to "Delete album", user_album_path(@user, @album), :method => :delete, data: { confirm: "Are you sure you want to delete this album?" } %> |
					<%= link_to "View all albums", user_path(@user) %>
				<% end %>
			</div>

			<%= render :partial => "photos/photo", :collection => @photos %>

		</div>

		<div class="hostwrapper span2">
			<h3>Hosts:</h3>

			<%= render :partial => "users/profilepic", :collection => @album.users, :as => :user %>
			
		</div>

	</div>
</div>