config/routes.rb
Pholder::Application.routes.draw do
  

  resources :users do
    resources :friends
    resources :albums do
      resources :photos
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :destroy, :update]

  resources :friendships, only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  resources :home, only: [:create]

  match '/contact',   to: 'home#contact'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete

  root :to => "home#index"

end

app/views/layouts/_footer.html.erb
<footer id="bottomfooter" class="navbar navbar-fixed-bottom">
	<%= link_to "contact us", contact_path %>
</footer>

app/views/layouts/_header.html.erb
<nav class="clearfix">
	<% if !signed_in? %>
		<%= link_to "home", root_url %>
	<% else %>
		<%= link_to "my profile", current_user %>
		<%= link_to "edit profile", edit_user_path(current_user) %>
		<%= link_to "friends", user_friends_path(current_user) %>
	<% end %>

	<div class="rightnav">
		<% if signed_in? %>
			<%= link_to "active users", users_path %>
			<%= link_to "log out", signout_path, method: "delete", :id =>"logoutlink" %>
		<% else %>
			<%= link_to "sign up", new_user_path, :id => "signuplink" %>
			<%= link_to "log in", signin_path, :id => "loginlink" %>
		<% end %>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= complete_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "/favicon.ico?1" %>
</head>
<body class="clearfix">
	<div class="bigwrapper clearfix">

		<%= render 'layouts/header' %>

		<div id="body" class="clearfix">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>

			<%= yield %>
		</div>
		
		<%= render 'layouts/footer' %>

	</div>

</body>
</html>